### ISSUE TITLE
请问宝塔如何放行？

### ISSUE THREAD

**Issue by yburger** [ethanzhao2001/Mailer-Typecho#1]
我的宝塔默认没有安装Nginx防火墙，在开启异步的状态下无法触发发信。

然后我手动安装了Nginx防火墙免费版，按您在博客中体积的方法：在防火墙设置里关闭了“From-data协议”开关，情况依旧，在开启异步的状态下无法触发发信，只有关闭异步才正常。

**Comment by ethanzhao2001** [comment]
那你这就不是宝塔防火墙的问题啊，用没用CDN，也有可能是CDN拦截了请求。或者是其他原因（目前最多的原因就是各类防火墙拦截掉了），异步就是typecho请求自己，请求失败就不行。就是因为很多人各种原因用不了异步，我才加上了关闭异步模式😂。。。

**Comment by yburger** [comment]
我用了Cloudflare的CDN服务，不过他的拦截记录里没有发现相关记录，如果在CF放行应该设置哪种规则呢？
我尝试在 WAF（Web 应用程序防火墙）内设置了这种放行规则，没有起到效果（马赛克内是我的VPS的IP地址）
![image](https://user-images.githubusercontent.com/11057647/212459486-24e41a4d-5115-48fb-b76b-b99f8a7531ad.png)

**Comment by ethanzhao2001** [comment]
设置本机IP放行应该是可以的

**Comment by yburger** [comment]
控制变量排查了一天发现是实际情况是，没有开启任何防火墙，开启异步功能的情况下，通过https访问，进行评论回复**不会**触发发送邮件；通过http访问，进行评论回复才**会**触发发送邮件，大佬有什么头绪吗？

**Comment by ethanzhao2001** [comment]
你没有开启强制https吗？

**Comment by yburger** [comment]
本来是开启了强制https的，今天为了弄清啥问题，重装了一下，把能开关的功能全都对照测试了一下，才发现的这个问题

**Comment by ethanzhao2001** [comment]
你这还没见过，可以加我Q 1592949305 细聊，在这时效性太低了

**Comment by yburger** [comment]
谢谢老哥，不过我不准备折腾了，试了一下lnmp上使用正常，把lnmp的Nginx配置和vhost配置搬宝塔上还是发不了信，不知道宝塔犯什么毛病，我直接转lnmp保平安了，不折腾了
